// default package
// Generated 08.02.2017 19:54:05 by Hibernate Tools 5.2.0.CR1

/**
 * Schoes generated by hbm2java
 */
public class Schoes implements java.io.Serializable {

	private Integer id;
	private String title;
	private int price;
	private String category;
	private String rating;
	private String labels;
	private String description;

	public Schoes() {
	}

	public Schoes(String title, int price, String category, String rating) {
		this.title = title;
		this.price = price;
		this.category = category;
		this.rating = rating;
	}

	public Schoes(String title, int price, String category, String rating, String labels, String description) {
		this.title = title;
		this.price = price;
		this.category = category;
		this.rating = rating;
		this.labels = labels;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getLabels() {
		return this.labels;
	}

	public void setLabels(String labels) {
		this.labels = labels;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
