// default package
// Generated 08.02.2017 19:54:05 by Hibernate Tools 5.2.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private UsersId id;

	public Users() {
	}

	public Users(UsersId id) {
		this.id = id;
	}

	public UsersId getId() {
		return this.id;
	}

	public void setId(UsersId id) {
		this.id = id;
	}

}
