// default package
// Generated 08.02.2017 19:54:05 by Hibernate Tools 5.2.0.CR1

/**
 * UsersId generated by hbm2java
 */
public class UsersId implements java.io.Serializable {

	private String login;
	private String role;
	private String name;
	private String email;
	private String phone;
	private String foto;
	private String password;

	public UsersId() {
	}

	public UsersId(String login, String role, String email, String password) {
		this.login = login;
		this.role = role;
		this.email = email;
		this.password = password;
	}

	public UsersId(String login, String role, String name, String email, String phone, String foto, String password) {
		this.login = login;
		this.role = role;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.foto = foto;
		this.password = password;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null && castOther.getLogin() != null
				&& this.getLogin().equals(castOther.getLogin())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null && castOther.getRole() != null
						&& this.getRole().equals(castOther.getRole())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getFoto() == castOther.getFoto()) || (this.getFoto() != null && castOther.getFoto() != null
						&& this.getFoto().equals(castOther.getFoto())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result + (getRole() == null ? 0 : this.getRole().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getFoto() == null ? 0 : this.getFoto().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		return result;
	}

}
