
package by.training.soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import by.training.soap.service.interfaces.ObjectFactory;
import by.training.soap.service.interfaces.ShoesCost;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GoodShoes", targetNamespace = "http://interfaces.service.soap.training.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GoodShoes {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShoesPrice", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.GetShoesPrice")
    @ResponseWrapper(localName = "getShoesPriceResponse", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.GetShoesPriceResponse")
    @Action(input = "http://interfaces.service.soap.training.by/GoodShoes/getShoesPriceRequest", output = "http://interfaces.service.soap.training.by/GoodShoes/getShoesPriceResponse")
    public int getShoesPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setShoesPrice", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.SetShoesPrice")
    @ResponseWrapper(localName = "setShoesPriceResponse", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.SetShoesPriceResponse")
    @Action(input = "http://interfaces.service.soap.training.by/GoodShoes/setShoesPriceRequest", output = "http://interfaces.service.soap.training.by/GoodShoes/setShoesPriceResponse")
    public boolean setShoesPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        ShoesCost arg0);

    /**
     * 
     * @return
     *     returns java.util.List<by.training.soap.service.interfaces.ShoesCost>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPrices", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.GetAllPrices")
    @ResponseWrapper(localName = "getAllPricesResponse", targetNamespace = "http://interfaces.service.soap.training.by/", className = "by.training.soap.service.interfaces.GetAllPricesResponse")
    @Action(input = "http://interfaces.service.soap.training.by/GoodShoes/getAllPricesRequest", output = "http://interfaces.service.soap.training.by/GoodShoes/getAllPricesResponse")
    public List<ShoesCost> getAllPrices();

}
